[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Set environment variables for the build process
  # These should also be set in the Netlify UI for security and dynamic values.
  # Example:
  # GOOGLE_API_KEY = "your_gemini_api_key_here"
  # PORT = "5000"
  # NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
